### Array in python

In [1]:
a = [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


### Array in Numpy

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


### Addition of two Numbers in python

In [5]:
a = [1,2,3]
b = [4,5,6]
z = []
for i in range(len(a)):
    z.append(a[i] + b[i])
print(z)

[5, 7, 9]


### Addition of two Numbers in Numpy

In [6]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


### Arithematic Operation in Numpy

In [8]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a ** b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


### NDarray Attributes

In [15]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[[1,2],[3,4],[5,6]]])
print(arr)
print(arr1)
print(arr2)
print(arr1.shape)
print(arr1.ndim)
print(arr.size)
print(arr1.size)
print(arr2.dtype)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]
  [5 6]]]
(2, 3)
2
5
6
int64


### Array Creation in numpy

In [12]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.zeros(5)
print(a)
print(b)
c = np.zeros((2,2))
print(c)
d = np.ones(3)
print(d)
e = np.ones((2,3))
print(e)
f = np.arange(100)
print(f)
g = np.arange(1,10,2)
print(g)
h = np.linspace(0,20,6)
print(h)
print(np.random.rand(5))
print(np.random.randint(1,100,6))
print(np.random.randn(5))

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[1 3 5 7 9]
[ 0.  4.  8. 12. 16. 20.]
[0.98379668 0.37290272 0.30552444 0.6778997  0.42000707]
[62  5 16 40 48 11]
[-0.07660363 -1.23881758 -1.03359945  0.38758311  0.16017526]


### numpy indexing and slicing

In [25]:
import numpy as np
a = np.array([10,20,30,40,50,60,67])
#1d array indexing
print(a[2])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
#2d array indexing
print(b[1][1])
#1d slicing
print(a[2:7])
print(a[::1])
print(a[:4])
#2d slicing
print(b[1])
print(b[:,1])
print(a[a>50])
print(a[a<50])
print(a[[0,4,3,6]])
print(a[a%2 == 0])
a[4] = 1000
print(a)

30
5
[30 40 50 60 67]
[10 20 30 40 50 60 67]
[10 20 30 40]
[4 5 6]
[2 5 8]
[60 67]
[10 20 30 40]
[10 50 40 67]
[10 20 30 40 50 60]
[  10   20   30   40 1000   60   67]


### Mathematical Operation in numpy

In [28]:
import numpy as np
# 1d broadcasting
a = np.array([1,2,3])
print(a+10)
# 2d broadcasting
b = np.array([[1,2,3],[4,5,6]])
print(b+10)
print(b+a)
# always no of columns must be same

[11 12 13]
[[11 12 13]
 [14 15 16]]
[[2 4 6]
 [5 7 9]]


### Matrix operation

In [35]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[4,3],[2,1]])
print(a*b)
print(np.dot(a,b))
print(a@b)
print(np.matmul(a,b))
print(a.T)

[[4 6]
 [6 4]]
[[ 8  5]
 [20 13]]
[[ 8  5]
 [20 13]]
[[ 8  5]
 [20 13]]
[[1 3]
 [2 4]]


### Universal Matrix Operation

In [38]:
import numpy as np
a = np.array([4,9,16])
print(np.sqrt(a))
b = np.array([-5,-6,-2,-8])
print(np.abs(b))
print(np.log(a))
print(np.exp(a))

[2. 3. 4.]
[5 6 2 8]
[1.38629436 2.19722458 2.77258872]
[5.45981500e+01 8.10308393e+03 8.88611052e+06]


### Numerical function

In [4]:
#round function 
import numpy as np
arr = np.array([1.234,5.674])
print(np.round(arr,2))
print(np.floor(arr))
print(np.ceil(arr))

[1.23 5.67]
[1. 5.]
[2. 6.]


### Statistical Function

In [4]:
import numpy as np
a = np.array([10,2,3,40,50])
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))
print(np.percentile(a,20))
print(np.var(a))
print(np.argmin(a))
print(np.argmax(a))
b = np.array([1,2,3,4,5])
c = np.array([10,8,6,4,2])
print(np.corrcoef(b,c))
#aggregate Function
d = np.array([[1,3,4],[5,6,8]])
print(np.sum(d))
print(np.sum(d,axis = 0))
print(np.sum(d,axis = 1))

21.0
10.0
20.039960079800558
50
2
2.8
401.6
1
4
[[ 1. -1.]
 [-1.  1.]]
27
[ 6  9 12]
[ 8 19]


### Question to answer
*1. Create 2D NumPy array of student scores; compute class average, highest scorer, normilize scores to 0-1 range*

In [21]:
import numpy as np
a = np.array([[89,74,90],[30,67,40]])
avr = np.mean(a)
h_s = np.max(a)
n = (a-np.min(a)) /(np.max(a) - np.min(a))
print("Student Score:",a)
print("Average Score:",avr)
print("Highest Score:", h_s)
print("Normalization Score:",n)



Student Score: [[89 74 90]
 [30 67 40]]
Average Score: 65.0
Highest Score: 90
Normalization Score: [[0.98333333 0.73333333 1.        ]
 [0.         0.61666667 0.16666667]]


In [22]:
import numpy as np
arr = np.array([[99,67,89],[87,68,90],[56,85,78],[45,92,91]])
avg = np.mean(arr)
print(avg)
high = np.sum(arr,axis = 1)
print(high)
mi = np.min(high)
print(min)
ma = np.max(high)
print(max)
t = np.sum(arr)
n = (arr - arr.min()) / arr.max() - arr.min()
print(n)
sub = np.mean(arr,axis = 0)
print(sub)

78.91666666666667
[255 245 219 228]
<built-in function min>
<built-in function max>
[[-44.45454545 -44.77777778 -44.55555556]
 [-44.57575758 -44.76767677 -44.54545455]
 [-44.88888889 -44.5959596  -44.66666667]
 [-45.         -44.52525253 -44.53535354]]
[71.75 78.   87.  ]


*2. Given arr = np.array([10,20,30,40,50]), write numpy expressions to get all elements > 25 and compute their sum*